{{- if and .Values.haulerRegistry.enabled .Values.haulerRegistry.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hauler-registry
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hauler.labels" . | nindent 4 -}}
    {{- with .Values.hauler.labels -}}
{{ toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.haulerRegistry.ingress.labels -}}
{{ toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.hauler.annotations -}}
{{ toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.haulerRegistry.ingress.annotations -}}
{{ toYaml . | nindent 4 }}
    {{- end }}
spec:
  rules:
  - host: {{ .Values.haulerRegistry.ingress.hostname }}
    http:
      paths:
      - backend:
          service:
            name: hauler-registry
            port:
              number: {{ .Values.haulerRegistry.service.ports.targetPort }}
        path: /
        pathType: Prefix
  {{- if .Values.haulerRegistry.ingress.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.haulerRegistry.ingress.hostname }}
    secretName: {{ .Values.haulerRegistry.ingress.tls.secretName }}
  {{- end }}
{{- end }}
