name: Lint and Test Workflow

on:
  workflow_dispatch:
  push:
  pull_request:
    branches:
      - 'main'

jobs:
  test-hauler-helm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Set Up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.17.1

      - name: Set Up Python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: '3.x'
          check-latest: true

      - name: Set Up Helm Chart Testing
        uses: helm/chart-testing-action@v2.7.0

      - name: Run Chart Testing
        run: ct lint --target-branch ${{ github.event.repository.default_branch }} --all --config ct.yaml

      - name: Set Up k3s
        run: curl -sfL https://get.k3s.io | sh - ; mkdir ~/.kube ; sudo cp /etc/rancher/k3s/k3s.yaml ~/.kube/config ; sudo chown runner ~/.kube/config

      - name: Wait for k3s
        run: |
          while ! kubectl get po -n kube-system -l app.kubernetes.io/name=traefik -ojsonpath='{.items[*].status.containerStatuses[*].ready}' | grep -q true
          do
          sleep 1
          done
          kubectl get nodes